### ISSUE TITLE
where to find the mp_username and mp_password

### ISSUE THREAD

**Issue by imramsuthakar** [MOLPay/molpay-mobile-xdk-android#14]
Hi,

 We are using the android molpay SDK in our app, while opening the payment gateway it throws the following error

 **MPMainUIWebClient jsonResult = {"Error":"Communication Error, please check internet connection, username, or password"}**

We don't know where to find the **mp_username and mp_password,** can you tell us the exact way from where to we find out this one 

The code we are using the following lines

// Mandatory String. Values obtained from MOLPay.
   **paymentDetails.put(MOLPayActivity.mp_username, "username");
   paymentDetails.put(MOLPayActivity.mp_password, "password");**

 Kindly solve this problem as soon as possible.

Thanks!

**Comment by clewlb** [comment]
Thanks for reaching out. You will need a valid merchant credentials or a sandbox credentials to use our plugin, you may send your request to sales-sa@razer.com or support-sa@razer.com to ask for one to be created for you. Otherwise, if you just want to try our plugin offline without using a valid credentials, just pass the parameter below to the XDK.

paymentDetails.put(MOLPayActivity.mp_sandbox_mode, true);

Thanks.
